### ISSUE TITLE
BUG: Extraneous files generated when creating data delivery pipeline in the same hierarchy with non aiSSEMBLE generated pipelines

### ISSUE THREAD

**Issue by ekoniec1** [boozallen/aissemble#132] opened 2024-06-10 18:06 UTC
## Description
If non-aiSSEMBLE modules are contained within a project's `pipelines` Maven module hierarchy, the source code for aiSSEMBLE defined pipelines is incorrectly generated into each `pipelines` sub-module.  For example, note the following `-pipelines` hierarchy for project `baz` where `foo-aissemble-pipeline` is an aiSSEMBLE metamodel defined pipeline and `bar-non-aissemble-pipeline` is **not** an aiSSEMBLE pipeline:
```

baz/
├─ baz-pipeline-models/
│  ├─ src/
│  │  ├─ main/
│  │  │  ├─ resources/
│  │  │  │  ├─ pipelines/
│  │  │  │  │  ├─ FooAissemblePipeline.json  
├─ baz-pipelines/
│  ├─ bar-non-aissemble-pipeline/
│  │  ├─ pom.xml
│  │  ├─ foo-aissemble-pipeline/ <--- aiSSEMBLE pipeline incorrectly generated here
│  │  │  ├─ pom.xml
│  ├─ foo-aissemble-pipeline/ <--- aiSSEMBLE pipeline correctly generated
│  │  │  ├─ pom.xml
```
## Steps to Reproduce
1. Create a new aiSSEMBLE project
2. Manually add a new module to the `*-pipelines` parent hierarchy.  This defect was reproduced using a non aiSSEMBLE pipeline Habushu module.
3. Create any aiSSEMBLE data delivery pipeline and following the build output prompts.  Note how the pipeline is generated into both `bar-pipelines` (which is expected), and under `bar-non-aissemble-pipeline` (which is not expected/desired).

## Expected Behavior
aiSSEMBLE and non-aiSSEMBLE pipelines may be used and defined together within the same Maven module hierarchy.  Specifically, aiSSEMBLE pipeline source code should only be generated directly under the `*-pipelines` module and **not** under any sub-modules within `*-pipelines`

## Actual Behavior
aiSSEMBLE pipeline scaffolding is incorrectly generated into both `*-pipelines` and all sub-modules within `*-pipelines`.  As a result, extraneous files are generated that developers must add to `.gitignore` and extraneous/incorrect build notifications are emitted - both of which may be confusing for developers.

## Additional Context

aiSSEMBLE version: 1.6.1

**Comment by jaebchoi** [comment] 2024-09-12 20:33
Recreated in 1.7.0 and 1.8.0 as you can see from the screenshot


<img width="434" alt="1 7 0 recreated" src="https://github.com/user-attachments/assets/8a16f7c8-4d98-4992-9e25-9133d4e02f83">



Couldn't reproduce in 1.9.0-SNAPSHOT. Therefore, fix will be introducing in 1.9.0


<img width="802" alt="1 9 0-snapshot resolved" src="https://github.com/user-attachments/assets/81ad406a-482f-4a80-a210-5b5e636f5867">

**Closed by jaebchoi** 2024-09-12 20:33 UTC
Labels: bug
