### ISSUE TITLE
Feature: Update the pipeline-invocation-service to package dependency jar files into zip files 

### ISSUE THREAD

**Issue by J-Clingerman** [boozallen/aissemble#264] opened 2024-08-07 16:11 UTC
## Description
In the past we have packaged dependency jar files using the uber-jar pattern. This has turned out to be problematic for downstream projects due to how plugin.xml is compiled. For this reason, we now package them into a zip file. 

pipeline-invocation-service

## DOD
- [x] Package pipeline-invocation-service app in its respective docker container without using an uber-jar
- [x] Ensure extension pipeline invocation service and extension docker aiSSEMBLE build is successful.
- [x] Run integration test.
- [x] Run archetype test.
- [x] Test to ensure that pipeline-invocation-service is functioning correctly by hitting their endpoints in downstream projects

## Test Strategy/Script

Part 1: Successful Build 

1.Clone aissemble or navigate to your aissemble directory

`git clone https://github.com/boozallen/aissemble.git
`
2. Compile the extensions-pipeline-invocation-service and extensions-docker modules

```
mvn clean install -pl :extensions-pipeline-invocation-service -am -Dmaven.build.cache.enabled=false 
mvn clean install -pl :extensions-docker -am -Dmaven.build.cache.enabled=false 
```

Part 2: Project setup

Create a downstream project using the below command. You can call it whatever you want but since issue264 will appear in some of the paths, that might be best left alone: 
```
mvn archetype:generate \
-DarchetypeGroupId=com.boozallen.aissemble \
-DarchetypeArtifactId=foundation-archetype \
-DarchetypeVersion=1.9.0-SNAPSHOT \
-DgroupId=com.issue264 \
-DartifactId=issue264 \
-DprojectGitUrl=url \
-DprojectName=issue264 
```

Add the below SimpleDataDeliveryExample.json pipeline to issue264-pipeline-models/src/main/resources/pipelines
```
{
    "name":"SimpleDataDeliveryExample",
    "package":"com.boozallen.aissemble.documentation",
        "type":{
            "name":"data-flow",
            "implementation":"data-delivery-spark"
        },
    "steps":[
    {
        "name":"IngestData",
        "type":"synchronous",
        "dataProfiling":{
            "enabled":false
        }
    }
    ]
}
```
Run mvn clean install and resolve all manual steps

Run the command and wait for the resources to be set up:

- Before you tilt up you need to add the following two files into your local:
- Create a templates folder under issue264/issue264-deploy/src/main/resources/apps/spark-operator
- Under the new folder, add the rbac.yaml file attached to this ticket
- Update your values.yal file under, issue264/issue264-deploy/src/main/resources/apps/spark-operator/values.yaml with the values.yaml file attached to this ticket
-
`tilt up
`
When you tilt up you will get a warning about adding allow_duplicates=true into your Tiltfile. Make sure you add allow duplicates to the line it says

Once the resources are complete, run a health check and trigger the pipeline-invocation-service:
Health check
The service can be accessed through an HTTP GET request
    - Using Postman
        - Set the URL to * http://localhost:8085/invoke-pipeline/healthcheck*
        - Set the Action to {}GET{}
You should see: Service Available in the bottom section of Postman

Trigger the pipeline-invocation-service:

 - The service can be accessed through an HTTP POST request
    - Using Postman
        - Set the URL to *http://localhost:8085/invoke-pipeline/start-spark-operator-job*
        - Set the Action to {}POST{}
        - Set the body type tp JSON
        - Set the body content to:  {"applicationName": "simple-data-delivery-example",  "profile": "dev"}
        
To confirm that the `simple-processing-pipeline` was installed successfully, you should see the following log: 
 

```
NAME: simple-data-delivery-example  
LAST DEPLOYED: <Date of deployment>     
NAMESPACE: default     
STATUS: deployed     
REVISION: 1     
TEST SUITE: None

```

**Comment by chang-annie** [comment] 2024-08-13 18:08
All test steps are passing! 

- built aissemble extensions-pipeline-invocation-service and extensions-docker modules 
- generated downstream project, added sample pipeline, and built successfully 
- tilt up successfully 
- Note: there seems to be an issue with the maven build cache for downstream projects. Building the project with the cache enabled results in two errors when tilting up. Both have to do with missing folders/directories
- For purposes of this ticket, the workaround was to build the downstream project with the build cache enabled. A bug ticket will be created to address/look into this
- `spark-worker-image` fails to build because it's missing the `/target/dockerbuild/wheels/` folder
```[ 4/10] COPY ./target/dockerbuild/wheels/. /tmp/wheels/```
- `policy-decision-point` image fails to build because `target/aissemble-security.properties` is missing
``` [2/2] COPY ./target/aissemble-security.properties /deployments/krausening/ ```
- added new `templates/rbac.yaml` file and updated `values.yaml` for `spark-operator`
- ran pipeline invocation service healthcheck endpoint 
- ran pipeline invocation service endpoint 
- confirmed successful log in pipeline invocation service pod

**Comment by J-Clingerman** [comment] 2024-08-14 18:03
Didnt build aissemble after PR was closed, so need to redo the final test but only Part 2.

**Comment by chang-annie** [comment] 2024-08-14 18:52
closing issue as test steps are passing again

**Closed by chang-annie** 2024-08-14 18:52 UTC
Labels: enhancement
